language: ruby
rvm: 3.2.5
dist: focal
group: edge
sudo: required

cache:
  bundler: true
  directories:
  - ${HOME}/perl5
  - ${HOME}/.cache

services:
- redis-server
- postgresql

env:
  global:
  - DATABASE_URL='postgres://localhost:5432/job_board_test'
  - RUBYOPT=-W0
  matrix:
  - INTEGRATION_SPECS='1' COVERAGE='1'
  - INTEGRATION_SPECS='0'

before_install:
- script/install-sqitch
- eval "$(perl -I ~/perl5/lib/perl5/ '-Mlocal::lib')"
- psql -c 'select version()'
- gem install bundler -v 2.5.11

before_script:
- createdb job_board_test
- sqitch deploy
- sqitch verify
